# Generated by Django 4.1.4 on 2022-12-15 18:32

from django.db import migrations, models
import django.db.models.deletion
import eapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catogery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to=eapp.models.getfilename)),
                ('discription', models.TextField(max_length=500)),
                ('sratus', models.BooleanField(default=False, help_text='0-shoe,1-hidden')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('product_images', models.ImageField(upload_to=eapp.models.getfilename)),
                ('quantity', models.IntegerField()),
                ('orginal_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('discription', models.TextField(max_length=500)),
                ('sratus', models.BooleanField(default=False, help_text='0-shoe,1-hidden')),
                ('trending', models.BooleanField(default=False, help_text='0-default,1-trending')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('catogery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.catogery')),
            ],
        ),
    ]
