# Generated by Django 4.1.4 on 2022-12-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catogery',
            name='sratus',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sratus',
        ),
        migrations.AddField(
            model_name='catogery',
            name='status',
            field=models.BooleanField(default=False, help_text='0-show,1-hidden'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, help_text='0-show,1-hidden'),
        ),
    ]
